### ISSUE TITLE
gulp dist should exit with errorcode on build error

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet-toolbox#12]
Moving issue from grommet core project (https://github.com/grommet/grommet/issues/220)

Submitted by @kylebyerly-hp

Found while changing node version.

Anytime that you change node version you have to rebuild any item with node-gyp.

Similar reproduction without having to change node-version for easy fix

```
npm i && rm -rf node_modules/node-sass && gulp dist
# should return non zero, returns 1
echo $?
```

**Comment by alansouzati** [comment]
can you validate this is still an issue @kylebyerly-hp  ?

**Comment by alansouzati** [comment]
Closing for now. Feel free to reopen if you still think this is an issue.
