### ISSUE TITLE
Debugging (source maps) does not work as expected

### ISSUE THREAD

**Issue by OlegZee** [grommet/grommet-toolbox#21]
Well, under Chrome it does not show jsx files so I have to deal with babelized javascript.
Now I'm using
```
	webpack: {
		devtool: 'eval-source-map'
        }
```
entry in mu grommet-toolbox.config.js and it does solve the issue but brings the other one - `gulp dist` now produces 13Mb file because of source maps are included for production build.

What is the correct and optimal way to get things right?

**Comment by alansouzati** [comment]
Good point. I believe for dev only, the devtools should be added. 

Grommet-toolbox currently has a limitation of one webpack config for both development and production. I believe we need to refactor it to add an additional entry for dev mode.

In the meantime, I will work on add the `eval` for the dev server.

Thanks for reporting this.

**Comment by alansouzati** [comment]
Support added in https://github.com/grommet/grommet-toolbox/commit/084e27ff38e47167343c591c0df1b1c0ef23d2d2.

Again, thanks for your contribution.
