### ISSUE TITLE
Cannot set extension resolution for jsx files

### ISSUE THREAD

**Issue by OlegZee** [grommet/grommet-toolbox#22]
I used to drop module extension in my sources such as:
```
import LoginForm from '../components/LoginForm';
```

However adding:
```
	webpack: {
	resolve: {
		extensions: ['', '.jsx', '.js', '.scss', '.css']
	}
	}
```
does not work because these settings are always overridden by predefined settings.

**Comment by alansouzati** [comment]
We recently fixed this in here: https://github.com/grommet/grommet-toolbox/commit/79ad551b30032f6c94e573e2988a1a271033a0c9

Are you using the latest grommet-toolbox (0.2.7)?

It was part of 0.2.5 release:

https://github.com/grommet/grommet-toolbox/releases/tag/v0.2.5

**Comment by alansouzati** [comment]
Also based on your list, we have them all in the new release as well.

**Comment by OlegZee** [comment]
Thank you!
installing grommet-toolbox@0.2.7 --save-dev did the trick. No need in customizing extensions anymore.
However please note 0.1.27 is current version on npm.
