### ISSUE TITLE
Avoid use of cache mechanism

### ISSUE THREAD

**Issue by gustahrodrigues** [grommet/grommet-toolbox#24]
Usually implementation of cache mechanism (like gulp-cache) relies on inotify to detect file changes, but there are some issues regarding the shared folder among host and VM.

Currently we are facing some instability issues because of that, mainly when we have host using different OS flavor.

In my current project, we are using VirtualBox and VMware.

VirtualBox issue: https://www.virtualbox.org/ticket/10660

**Comment by alansouzati** [comment]
good point.

@michaelgilley @nickjvm I would appreciate your input in here.

I've seen multiple folks complaining about this. So, I'm leaning towards removing gulp-cache.

**Comment by michaelgilley** [comment]
That's strange behavior. I can say that caching has saved us lots of time from having to lint files that haven't even been updated so I'd definitely argue for keeping it. But either way, it'd be better to have this option configurable. Perhaps we can add a shut-off option to disable lint caching for those whose set up won't support it?

**Comment by alansouzati** [comment]
I like the idea of making it configurable option. @gustahrodrigues would you be willing to submit a PR for that?

**Comment by alansouzati** [comment]
Added support for that in https://github.com/grommet/grommet-toolbox/commit/084e27ff38e47167343c591c0df1b1c0ef23d2d2.

See lintCache option in the README: https://github.com/grommet/grommet-toolbox#options
