### ISSUE TITLE
Scsslint default option is wrong

### ISSUE THREAD

**Issue by gustahrodrigues** [grommet/grommet-toolbox#26]
Readme file says that scsslint default value is `false`, but actually the default option value is `true` https://github.com/grommet/grommet-toolbox/blob/master/src/gulp-options-builder.js#L24.

Which one is right?

**Comment by alansouzati** [comment]
Thanks for the catch. I've updated the docs. In the past, it used to be default to false because scss linting required ruby. Now that it is a node-only project we've changed the default but forgot to update the docs, shame on me 😢
