### ISSUE TITLE
Grommet-toolbox references outdated gulp-eslint which results in eslint issues with flow type

### ISSUE THREAD

**Issue by OlegZee** [grommet/grommet-toolbox#28]
The issue is described as https://github.com/eslint/eslint/issues/5211

**Comment by alansouzati** [comment]
Good catch. Do you want to craft a Pull Request that solves this?

I'm happy to work on it to if you prefer.

**Comment by OlegZee** [comment]
@alansouzati I've made a try. However most recent gulp-eslint references eslint 3.0.0 while we need 3.2.0. I have no idea how to resolve this other that forking gulp-eslint and making PR and waiting if and when they accept it.
Are there any shortcuts?

**Comment by alansouzati** [comment]
Actually they use the `^` which should be good for what we need:

https://github.com/adametry/gulp-eslint/blob/master/package.json#L44

`npm install gulp-eslint@3.0.1` will use `eslint@3.2.2`.

**Comment by bryanjacquot** [comment]
@OlegZee if you're able to create a PR for grommet-toolbox and update this line: https://github.com/grommet/grommet-toolbox/blob/master/package.json#L37 with 3.0.0 then it will pull in the latest eslint since they are using a `^` in their dependency.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet-toolbox/commit/c71e1c83fe3429f32cab706cbcfd77d00732c0a1
