### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by primozs** [grommet/grommet-toolbox#3]
I cant get to work hot reload. I was also testing on grommet-todo, grommet-blog. It does not work anywhere.

**Comment by alansouzati** [comment]
Im experiencing the same issue as well. Let me look into this.

Kr
Alan

**Comment by alansouzati** [comment]
FYI the issue with Hot Reloading is only when using ES6 classes. React Hot loader as of this moment does not support this feature. I'm following this thread to see when react-hot-loader 3 will be officially released.

https://github.com/gaearon/react-hot-loader/pull/240

**Comment by Beelal** [comment]
@alansouzati 
[react-project.zip](https://github.com/grommet/grommet-toolbox/files/280413/react-project.zip)
I have created sample react app using ES6 classes with webpack hot loader and hot reloading is working. I have attached sample project. Thanks.

**Comment by alansouzati** [comment]
thanks for sharing this project @Beelal.

Let me download it and see what is missing in grommet-toolbox 👍

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet-toolbox/commit/6d04e56dedf297507cfd606a8c2c80e72b16e382.

Grommet-toolbox 0.1.26 released with the fix.

Big shout out to @Beelal for sharing his project.
