### ISSUE TITLE
setupJsDom breaks other node plugins.

### ISSUE THREAD

**Issue by vivekmoosani** [grommet/grommet-toolbox#31]
setupJsDom function in gulp-tasks-tests.js breaks other node modules (for example 'require.js').
This is the reference to the function https://github.com/grommet/grommet-toolbox/blob/master/src/gulp-tasks-test.js#L10

As the function pollutes the node global object, other modules could wrongly interpret the environment they are being executed as browser instead of node.js like 'requirejs' does.

**Comment by bryanjacquot** [comment]
This has been resolved by the [v0.3.0](https://github.com/grommet/grommet-toolbox/releases/tag/v0.3.3) release.  This release uses Jest which has a built-in JSDom.
