### ISSUE TITLE
Improvement: Create an option to do not minify the code for debugging

### ISSUE THREAD

**Issue by gustahrodrigues** [grommet/grommet-toolbox#33]
When we are working on some development, usually we get a JS error at Browser console.

Since our code is minified, it's hard to check which line that error occur.

Can we improve that?

**Comment by alansouzati** [comment]
`gulp dist --skipMinify` will do it. 

We have an Advanced Usage wiki where we describe this and other toolbox capabilities.

https://github.com/grommet/grommet-toolbox/wiki/Advanced-Usage#create-a-dist-without-minified-code
