### ISSUE TITLE
localization encoding

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet-toolbox#39]
submitting the issue after consulting with Alan.

The zh-CN.js file is being complied in a way that the characters are not encoded. I checked the type of the file I committed, and like all the others lang (that seems to work)  it is indeed in "UTF-8" so there shouldn't be any problem with encoding.

This is an example of the compiled file:
![image](https://cloud.githubusercontent.com/assets/6320236/19864842/9c4b37d6-9f5f-11e6-87a7-0e64c74ec506.png)

I'm thinking that the only thing that may cause it, is the build process that grommet is using. 
Please note that Japanese is working well.

Bests,
Shimi

**Comment by alansouzati** [comment]
Hey I'm trying to reproduce this issue but I'm not able too. where is the zh-CN file? is it inside your dist folder?

I tried running `gulp dist` inside grommet core and look at the messages and I cannot reproduce it, even in a windows environment.

This is the file that is actually inside grommet Stable branch and uses `gulp dist`

https://github.com/grommet/grommet/blob/stable/messages/zh-CN.js
