### ISSUE TITLE
eslint failAfterError very disruptive

### ISSUE THREAD

**Issue by tyrjo** [grommet/grommet-toolbox#42]
Running a grommet-toolbox based environment in a container. When I introduce a lint error, failAfterError causes gulp to exit, which then exits the container.

Instead, I want the error reported, and the environment to continue to watch for the next file change. Having to restart gulp after any error is really disruptive to the development workflow.

**Comment by alansouzati** [comment]
Are you using `gulp dev` or `gulp dist?`

**Comment by tyrjo** [comment]
gulp dev

**Comment by alansouzati** [comment]
which version of toolbox are you using? I thought I removed linting from gulp dev. I had a bunch of requests to remove it for the very same reason you are describing.

**Comment by alansouzati** [comment]
I'm closing this issue as I believe eslint is not running in development mode.
