### ISSUE TITLE
Is <AppContainer/> required as per react-hot-loader 3.x docs?

### ISSUE THREAD

**Issue by maysst** [grommet/grommet-toolbox#44]
As per [https://github.com/gaearon/react-hot-loader/tree/next-docs/docs](https://github.com/gaearon/react-hot-loader/tree/next-docs/docs) should the Grommet application templates include the `<AppContainer/>` wrapper?

**Comment by alansouzati** [comment]
This is definitely a good idea, but there are cases where people are using Grommet App with other frameworks and this approach would not work.

 I believe for now it is better to leave this to the caller so that he/she can decide where is the best place to apply hot reloading.

**Comment by maysst** [comment]
Hi Alan,

I can see your reasoning, but the grommet-toolbox CLI allows creation of a "new" app from a template.  Shouldn't the resulting "app" be able to be compiled and run straight away fresh out of the box? i.e. "gulp dev" and away we go?

Without reading the notes on the above, I'm not sure that everyone would know that <AppContainer/> would be even be required?

**Comment by alansouzati** [comment]
Definitely yes! I thought I added it to the template.

https://github.com/grommet/grommet-cli/blob/master/templates/full/src/js/index.js

I'm probably missing something though.

Did you use the full option?

**Comment by maysst** [comment]
Ahhhh.....now that could be the answer!  I used:

`grommet~$ new app --theme hpe --type empty`

Using `--type full` does indeed put the `<AppContainer/>` around the `<Main/>` component...

So, for reference (perhaps in the grommet-toolbox docs) could you clarify what the 3 types of app are?

:-)

**Comment by alansouzati** [comment]
I will make sure to add the hot reloading in the empty as well. As you said, it is important to use whatever template and work properly.

The different templates are described in the `grommet-cli` project itself

you can run `grommet new --help` and get the documentation regarding the options.

**Comment by alansouzati** [comment]
We have updated the CLI and hot reloading are made available without the AppContainer which is pretty cool. We are using `babel-preset-react-hmre`.

Check this video out where I go over the capabilities of the new CLI:

https://vimeo.com/199912095
