### ISSUE TITLE
Running gulp test normal globbing will run the entire test suite once for every file in the glob

### ISSUE THREAD

**Issue by coltonw** [grommet/grommet-toolbox#46]
If you have the config:
```
{
  testPaths: ['__tests__/**/*.js']
}
```
This will run the tests once for each file instead of just once.

**Comment by coltonw** [comment]
The workaround is to not use globbing at all and to use a path for the folder:
```
{
  testPaths: ['__tests__']
}
```
However, doing this is wrong by traditional globbing which means that none of your test files will be linted by eslint.

**Comment by alansouzati** [comment]
You could add the test path to the jsAssets which will run eslint. Could you please double check that?

I invite you to check out the new cli with the `grommet pack` and `grommet check` commands. All the configurations are exposed now and you can run jest CLI directly.

**Comment by coltonw** [comment]
Yeah, I should have commented earlier.  That is my intended solution.

Should we close this issue or leave it open as a known issue with no intention to fix it in this project?

The old king is dead, long live the king! 👑

**Comment by alansouzati** [comment]
I believe we can close it with the jsAssets work around. Even with a closed issue, it always be available for folks facing similar problems. Thoughts? I'm fine with leaving it open also.

**Comment by alansouzati** [comment]
I'm closing this in favor of the new CLI. specially with webpack v2 coming :)
